DELETE FROM enquiries;
DELETE FROM products;
INSERT INTO products (name, category, short_desc, long_desc, price, image_url) VALUES
('Wireless Headphones', 'Electronics', 'Noise-cancelling wireless headphones with superior sound quality', 'Premium noise-cancelling wireless headphones with 30-hour battery life, Bluetooth 5.0 connectivity, memory foam ear cups, and built-in microphone for crystal clear calls. Perfect for travel, work, and entertainment.', 199.99, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&auto=format&fit=crop'),
('Smart Watch Pro', 'Electronics', 'Advanced fitness tracking smartwatch with GPS', 'Feature-rich smartwatch with heart rate monitoring, sleep tracking, GPS, water resistance up to 50m, 7-day battery life, and customizable watch faces. Syncs with both Android and iOS devices.', 299.99, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&auto=format&fit=crop'),
('Premium Coffee Maker', 'Home Appliances', 'Programmable coffee machine with thermal carafe', '12-cup programmable coffee maker with built-in grinder, thermal stainless steel carafe to keep coffee hot for hours, adjustable brew strength, and 24-hour programmable timer. Includes reusable filter.', 89.99, 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&auto=format&fit=crop'),
('Professional Yoga Mat', 'Fitness', 'Eco-friendly, non-slip exercise mat with alignment lines', 'Extra thick 6mm eco-friendly yoga mat with double-sided non-slip surface, alignment lines for perfect pose positioning, moisture-resistant top layer, and includes carrying strap. Perfect for all skill levels.', 34.99, 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=400&auto=format&fit=crop'),
('Adjustable LED Desk Lamp', 'Home Office', 'Energy-efficient LED desk lamp with adjustable brightness', 'Modern LED desk lamp with 5 levels of brightness adjustment, 3 color temperatures (warm to cool white), touch controls, flexible gooseneck design, USB charging port, and memory function for last setting.', 45.99, 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&auto=format&fit=crop'),
('Water-resistant Laptop Backpack', 'Travel', 'Durable backpack with laptop compartment and USB port', 'Weather-resistant backpack with dedicated 15.6" laptop compartment, multiple organizational pockets, USB charging port, hidden anti-theft pocket, comfortable padded straps, and luggage strap for travel.', 79.99, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&auto=format&fit=crop'),
('High-Speed Blender', 'Kitchen', 'Professional-grade blender with 8 preset programs', 'Powerful 1500W blender with 8 preset programs (smoothie, ice crush, soup, etc.), 64oz BPA-free pitcher, stainless steel blades, touch controls, self-cleaning function, and 7-year warranty.', 129.99, 'https://images.unsplash.com/photo-1553531889-56cc480ac5cb?w=400&auto=format&fit=crop'),
('Ceramic Plant Pot Set', 'Home Decor', 'Set of 3 ceramic plant pots with drainage', 'Set includes 3 ceramic plant pots in different sizes (6", 8", 10"), each with drainage holes and matching saucers. Made from premium clay with matte finish. Perfect for indoor plants and succulents.', 49.99, 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400&auto=format&fit=crop'),
('Ergonomic Office Chair', 'Home Office', 'Comfortable ergonomic chair with lumbar support', 'Premium ergonomic office chair with adjustable lumbar support, 3D armrests, 135-degree recline function, breathable mesh back, and smooth-rolling casters. Supports up to 250lbs weight capacity.', 189.99, 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&auto=format&fit=crop'),
('Portable Bluetooth Speaker', 'Electronics', 'Waterproof speaker with 12-hour battery', 'IPX7 waterproof Bluetooth speaker with 360-degree sound, 12-hour battery life, built-in microphone for hands-free calls, and pairing capability for stereo sound. Perfect for outdoor activities.', 69.99, 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&auto=format&fit=crop');
INSERT INTO enquiries (product_id, name, email, phone, message) VALUES
(1, 'John Smith', 'john@example.com', '+1 (555) 123-4567', 'Interested in bulk purchase for corporate gifts. Please send pricing for 50 units.'),
(3, 'Sarah Johnson', 'sarah@example.com', '', 'Do you offer international shipping for the coffee maker? What is the voltage requirement?'),
(5, 'Mike Wilson', 'mike@example.com', '+1 (555) 987-6543', 'Is the desk lamp available in black color? Also, what is the warranty period?'),
(2, 'Emily Davis', 'emily@example.com', '', 'Can the smartwatch track swimming activities? Does it have swim mode?'),
(8, 'Robert Brown', 'robert@example.com', '+1 (555) 456-7890', 'Looking to purchase multiple sets for our office. Do you offer quantity discounts?');


SELECT 'Products:' as Table_Name, COUNT(*) as Record_Count FROM products
UNION ALL
SELECT 'Enquiries:', COUNT(*) FROM enquiries;